CLASS_ID_TO_CATEGORY = {
    0: "apple",
    1: "asparagus",
    2: "avocado",
    3: "bacon",
    4: "bagel",
    5: "baked beans",
    6: "banana",
    7: "beef",
    8: "beetroot",
    9: "blueberry",
    10: "bread",
    11: "breakfast cereal",
    12: "broccoli",
    13: "brussels sprout",
    14: "cake",
    15: "capsicum",
    16: "carrot",
    17: "cauliflower",
    18: "celery",
    19: "cheese",
    20: "cherry",
    21: "chicken",
    22: "chocolate",
    23: "coconut",
    24: "crab",
    25: "cracker",
    26: "croissant",
    27: "cucumber",
    28: "curry",
    29: "doughnut",
    30: "duck",
    31: "dumpling",
    32: "eggplant",
    33: "fig",
    34: "fish",
    35: "french toast",
    36: "grape",
    37: "grapefruit",
    38: "ham",
    39: "hamburger",
    40: "hot dog",
    41: "ice cream",
    42: "kale",
    43: "kiwifruit",
    44: "lamb",
    45: "leek",
    46: "lettuce",
    47: "lime",
    48: "mandarin",
    49: "mango",
    50: "melon",
    51: "mexican taco",
    52: "milk",
    53: "muffin",
    54: "mulberry",
    55: "mushroom",
    56: "mussel",
    57: "nut",
    58: "olive",
    59: "omelette",
    60: "onion",
    61: "orange",
    62: "pancake",
    63: "passionfruit",
    64: "pasta",
    65: "pea",
    66: "peach",
    67: "pear",
    68: "persimmon",
    69: "pickles",
    70: "pie",
    71: "pineapple",
    72: "pizza",
    73: "plum",
    74: "pomegranate",
    75: "pork",
    76: "potato",
    77: "prawn",
    78: "pumpkin",
    79: "raspberry",
    80: "salad",
    81: "salmon",
    82: "sausage",
    83: "snow pea",
    84: "soft drink",
    85: "soup",
    86: "spam",
    87: "steak sandwich",
    88: "strawberry",
    89: "sweet potato",
    90: "sweetcorn",
    91: "tomato",
    92: "waffle",
    93: "yoghurt",
    94: "zucchini",
}
