repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        name: flake8
        additional_dependencies: []

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        additional_dependencies: []
        files: ^src/
        args: []

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: bash -c 'export $(grep -v "^#" env/test.env | xargs) && python -m pytest'
        language: system
        pass_filenames: false
        always_run: true
