"""create mety activity table

Revision ID: 127268442c60
Revises: be43c412e986
Create Date: 2025-05-01 14:00:37.929495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '127268442c60'
down_revision = 'be43c412e986'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_mety_level',
    sa.Column('activity_category', sa.String(length=100), nullable=False),
    sa.Column('specific_activity', sa.Text(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('mety_level', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index(op.f('ix_activity_mety_level_activity_category'), 'activity_mety_level', ['activity_category'], unique=False)
    op.create_index(op.f('ix_activity_mety_level_age'), 'activity_mety_level', ['age'], unique=False)
    op.create_index(op.f('ix_activity_mety_level_specific_activity'), 'activity_mety_level', ['specific_activity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_mety_level_specific_activity'), table_name='activity_mety_level')
    op.drop_index(op.f('ix_activity_mety_level_age'), table_name='activity_mety_level')
    op.drop_index(op.f('ix_activity_mety_level_activity_category'), table_name='activity_mety_level')
    op.drop_table('activity_mety_level')
    # ### end Alembic commands ###
