"""drop alcohol and caffeine nutrient

Revision ID: 14c502144422
Revises: 3852c4e4a3d9
Create Date: 2025-05-17 00:32:48.018141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14c502144422'
down_revision = '3852c4e4a3d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food_nutrient', 'alcohol_g')
    op.drop_column('food_nutrient', 'caffeine_mg')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_nutrient', sa.Column('caffeine_mg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('food_nutrient', sa.Column('alcohol_g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
