"""create daily_nutrient_intake, food_nutrient, ingredient_inventory and ingredient_nutrient models

Revision ID: 9059b518c791
Revises: 
Create Date: 2025-04-09 01:09:09.467153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9059b518c791'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_nutrient_intake',
    sa.Column('nutrient', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Enum('boy', 'girl', name='gender_enum'), nullable=False),
    sa.Column('intake', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('food_nutrient',
    sa.Column('food_name', sa.String(length=255), nullable=False),
    sa.Column('food_category', sa.String(length=100), nullable=True),
    sa.Column('food_detail', sa.Text(), nullable=True),
    sa.Column('energy_with_fibre_kj', sa.Float(), nullable=True),
    sa.Column('energy_without_fibre_kj', sa.Float(), nullable=True),
    sa.Column('moisture_g', sa.Float(), nullable=True),
    sa.Column('protein_g', sa.Float(), nullable=True),
    sa.Column('total_fat_g', sa.Float(), nullable=True),
    sa.Column('carbs_with_sugar_alcohols_g', sa.Float(), nullable=True),
    sa.Column('carbs_without_sugar_alcohols_g', sa.Float(), nullable=True),
    sa.Column('starch_g', sa.Float(), nullable=True),
    sa.Column('total_sugars_g', sa.Float(), nullable=True),
    sa.Column('added_sugars_g', sa.Float(), nullable=True),
    sa.Column('free_sugars_g', sa.Float(), nullable=True),
    sa.Column('dietary_fibre_g', sa.Float(), nullable=True),
    sa.Column('alcohol_g', sa.Float(), nullable=True),
    sa.Column('ash_g', sa.Float(), nullable=True),
    sa.Column('vitamin_a_retinol_ug', sa.Float(), nullable=True),
    sa.Column('beta_carotene_ug', sa.Float(), nullable=True),
    sa.Column('provitamin_a_equivalents_ug', sa.Float(), nullable=True),
    sa.Column('vitamin_a_re_ug', sa.Float(), nullable=True),
    sa.Column('thiamin_b1_mg', sa.Float(), nullable=True),
    sa.Column('riboflavin_b2_mg', sa.Float(), nullable=True),
    sa.Column('niacin_b3_mg', sa.Float(), nullable=True),
    sa.Column('niacin_equivalents_mg', sa.Float(), nullable=True),
    sa.Column('folate_natural_ug', sa.Float(), nullable=True),
    sa.Column('folic_acid_ug', sa.Float(), nullable=True),
    sa.Column('total_folates_ug', sa.Float(), nullable=True),
    sa.Column('dietary_folate_equivalents_ug', sa.Float(), nullable=True),
    sa.Column('vitamin_b6_mg', sa.Float(), nullable=True),
    sa.Column('vitamin_b12_ug', sa.Float(), nullable=True),
    sa.Column('vitamin_c_mg', sa.Float(), nullable=True),
    sa.Column('alpha_tocopherol_mg', sa.Float(), nullable=True),
    sa.Column('vitamin_e_mg', sa.Float(), nullable=True),
    sa.Column('calcium_mg', sa.Float(), nullable=True),
    sa.Column('iodine_ug', sa.Float(), nullable=True),
    sa.Column('iron_mg', sa.Float(), nullable=True),
    sa.Column('magnesium_mg', sa.Float(), nullable=True),
    sa.Column('phosphorus_mg', sa.Float(), nullable=True),
    sa.Column('potassium_mg', sa.Float(), nullable=True),
    sa.Column('selenium_ug', sa.Float(), nullable=True),
    sa.Column('sodium_mg', sa.Float(), nullable=True),
    sa.Column('zinc_mg', sa.Float(), nullable=True),
    sa.Column('caffeine_mg', sa.Float(), nullable=True),
    sa.Column('cholesterol_mg', sa.Float(), nullable=True),
    sa.Column('tryptophan_mg', sa.Float(), nullable=True),
    sa.Column('saturated_fat_g', sa.Float(), nullable=True),
    sa.Column('monounsaturated_fat_g', sa.Float(), nullable=True),
    sa.Column('polyunsaturated_fat_g', sa.Float(), nullable=True),
    sa.Column('linoleic_acid_g', sa.Float(), nullable=True),
    sa.Column('alpha_linolenic_acid_g', sa.Float(), nullable=True),
    sa.Column('epa_c20_5w3_mg', sa.Float(), nullable=True),
    sa.Column('dpa_c22_5w3_mg', sa.Float(), nullable=True),
    sa.Column('dha_c22_6w3_mg', sa.Float(), nullable=True),
    sa.Column('omega3_long_chain_total_mg', sa.Float(), nullable=True),
    sa.Column('trans_fatty_acids_mg', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredient_inventory',
    sa.Column('children_profile_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredient_inventory_children_profile_id'), 'ingredient_inventory', ['children_profile_id'], unique=False)
    op.create_table('ingredient_nutrients',
    sa.Column('food_nutrient_id', sa.String(length=36), nullable=False),
    sa.Column('ingredient_inventory_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['food_nutrient_id'], ['food_nutrient.id'], ),
    sa.ForeignKeyConstraint(['ingredient_inventory_id'], ['ingredient_inventory.id'], ),
    sa.PrimaryKeyConstraint('food_nutrient_id', 'ingredient_inventory_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingredient_nutrients')
    op.drop_index(op.f('ix_ingredient_inventory_children_profile_id'), table_name='ingredient_inventory')
    op.drop_table('ingredient_inventory')
    op.drop_table('food_nutrient')
    op.drop_table('daily_nutrient_intake')
    # ### end Alembic commands ###