"""create seasonal food table

Revision ID: 9c848cf3da58
Revises: e6a41883a20f
Create Date: 2025-05-11 18:57:42.586850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c848cf3da58'
down_revision = 'e6a41883a20f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seasonal_food',
    sa.Column('food_name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('season', sa.Enum('Spring', 'Summer', 'Autumn', 'Winter', name='season_enum'), nullable=False),
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seasonal_food_category'), 'seasonal_food', ['category'], unique=False)
    op.create_index(op.f('ix_seasonal_food_food_name'), 'seasonal_food', ['food_name'], unique=False)
    op.create_index(op.f('ix_seasonal_food_month'), 'seasonal_food', ['month'], unique=False)
    op.create_index(op.f('ix_seasonal_food_region'), 'seasonal_food', ['region'], unique=False)
    op.create_index(op.f('ix_seasonal_food_season'), 'seasonal_food', ['season'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seasonal_food_season'), table_name='seasonal_food')
    op.drop_index(op.f('ix_seasonal_food_region'), table_name='seasonal_food')
    op.drop_index(op.f('ix_seasonal_food_month'), table_name='seasonal_food')
    op.drop_index(op.f('ix_seasonal_food_food_name'), table_name='seasonal_food')
    op.drop_index(op.f('ix_seasonal_food_category'), table_name='seasonal_food')
    op.drop_table('seasonal_food')
    # ### end Alembic commands ###
