"""create food fun fact model

Revision ID: be43c412e986
Revises: 9059b518c791
Create Date: 2025-04-30 11:24:38.270289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be43c412e986'
down_revision = '9059b518c791'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_category_fun_fact',
    sa.Column('food_category', sa.String(length=100), nullable=False),
    sa.Column('fun_fact', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_category_fun_fact_food_category'), 'food_category_fun_fact', ['food_category'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_food_category_fun_fact_food_category'), table_name='food_category_fun_fact')
    op.drop_table('food_category_fun_fact')
    # ### end Alembic commands ###
