"""add db_category to seonsal food table

Revision ID: d37ac9ee3ce7
Revises: a181972d3344
Create Date: 2025-05-16 16:04:03.863603

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d37ac9ee3ce7"
down_revision = "a181972d3344"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First add the column as nullable
    op.add_column("seasonal_food", sa.Column("db_category", sa.String(), nullable=True))

    # Update existing rows with a default value (using the food_name as default)
    op.execute("UPDATE seasonal_food SET db_category = food_name")

    # Now alter the column to make it non-nullable
    op.alter_column("seasonal_food", "db_category", nullable=False)

    # Create index
    op.create_index(
        op.f("ix_seasonal_food_db_category"),
        "seasonal_food",
        ["db_category"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_seasonal_food_db_category"), table_name="seasonal_food")
    op.drop_column("seasonal_food", "db_category")
    # ### end Alembic commands ###
