"""create child energy requirement table

Revision ID: e6a41883a20f
Revises: 127268442c60
Create Date: 2025-05-01 18:04:28.633250

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e6a41883a20f"
down_revision = "127268442c60"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "child_energy_requirement",
        sa.Column("age", sa.Integer(), nullable=False),
        sa.Column(
            "gender",
            sa.dialects.postgresql.ENUM(name="gender_enum", create_type=False),
            nullable=False,
        ),
        sa.Column("unit", sa.String(length=50), nullable=False),
        sa.Column("physical_activity_level", sa.Float(), nullable=False),
        sa.Column("estimated_energy_requirement", sa.Float(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
    )
    op.create_index(
        op.f("ix_child_energy_requirement_age"),
        "child_energy_requirement",
        ["age"],
        unique=False,
    )
    op.create_index(
        op.f("ix_child_energy_requirement_gender"),
        "child_energy_requirement",
        ["gender"],
        unique=False,
    )
    op.create_index(
        op.f("ix_child_energy_requirement_physical_activity_level"),
        "child_energy_requirement",
        ["physical_activity_level"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_child_energy_requirement_physical_activity_level"),
        table_name="child_energy_requirement",
    )
    op.drop_index(
        op.f("ix_child_energy_requirement_gender"),
        table_name="child_energy_requirement",
    )
    op.drop_index(
        op.f("ix_child_energy_requirement_age"), table_name="child_energy_requirement"
    )
    op.drop_table("child_energy_requirement")
    # ### end Alembic commands ###
